version: 2

registries:
  github-maven:
    type: maven-repository
    url: https://maven.pkg.github.com/ParadoxV5/
    username: ''
    password: ${{ secrets.GITHUB_TOKEN }}
  github-rubygems:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/ParadoxV5
    token: ${{ secrets.GITHUB_TOKEN }}

updates:

- package-ecosystem: maven
  registries: [github-maven]
  directory: /
  ignore:
  - update-types: [version-update:semver-major]
    dependency-name: '*'
  schedule:
    interval: weekly
  assignees: [ParadoxV5]

- package-ecosystem: bundler
  registries: [github-rubygems]
  insecure-external-code-execution: allow
  directory: /
  ignore:
  - update-types: [version-update:semver-major]
    dependency-name: '*'
  schedule:
    interval: weekly
  assignees: [ParadoxV5]
