name: Java
on: workflow_dispatch
jobs:
  execute:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        cache: maven
    
    - name: Execute with Maven
      run: mvn compile exec:java
      env: {GITHUB_TOKEN: "${{ github.token }}"}